name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install golang
        run: wget https://golang.org/dl/go1.15.3.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go1.15.3.linux-amd64.tar.gz && export PATH=$PATH:/usr/local/go/bin

      - name: Run tests
        run: go test -v
        
      - name: Run tests -data race
        run: go test -race
